name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        federated-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      with:
        scope: resourceGroup
        resource-group: ${{ secrets.AZURE_RG }}
        template-file: src/InfrastructureAsCode/main.bicep
        deployment-name: TechExcelDeployment