name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, test, prod)'
        required: true
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        federated-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Bicep template
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/InfrastructureAsCode/main.bicep
        deploymentName: TechExcelDeployment-${{ github.event.inputs.environment }}
        parameters: |
          environment=${{ github.event.inputs.environment }}
        failOnStdErr: true